# Generated by Django 3.2 on 2022-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(max_length=3000, verbose_name='Текст задачи')),
                ('task_description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('state', models.CharField(choices=[('new', 'Новая'), ('in_process', 'В процессе'), ('done', 'Выполнено')], default='new', max_length=100, verbose_name='Состояние')),
                ('deadline', models.DateTimeField(default=None, null=True, verbose_name='Дедлайн')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
