# Generated by Django 3.2 on 2022-09-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('task_description', models.TextField(max_length=3000, verbose_name='Текст')),
                ('state', models.CharField(choices=[('New', 'Новая')], default='New', max_length=100, verbose_name='Статус')),
                ('deadline', models.DateTimeField(default=None, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
    ]
