# Generated by Django 3.2 on 2022-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_text', models.TextField(max_length=3000, verbose_name='Текст задачи')),
                ('state', models.CharField(default='new', max_length=300, verbose_name='Состояние')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
            ],
        ),
    ]
