# Generated by Django 3.2 on 2022-09-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(default='', max_length=3000, verbose_name='Описание'),
        ),
    ]
