# Generated by Django 3.2 on 2022-09-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_task_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дедлайн'),
        ),
    ]
